### ISSUE TITLE
Reporting bugs [disk timeout]

### ISSUE THREAD

**Issue by CaptainDoubleYou** [kzahel/jstorrent-legacy-app#12] opened 2013-12-30 06:52 UTC
I encounter multiple errors from time to time (every 1 hour or so). I get notifications in ChromeOS notification area. Is there a way to report those errors back to you?
I'm running latest dev version on my Chromebook Pixel. I have a screen shot that I took for some errors. Most of those errors are related to disk issues. I save the files to a folder in the downloads folder. Usually if I hit start on the torrent again, it continues downloading without a problem.

**Comment by kzahel** [comment] 2013-12-30 06:59
Awesome, thank you for the screenshot.
I actually just got back to the states and was testing on my Pixel and ran
into the same exact problem. I also just re-started and it worked just
fine. But I am not totally certain what the cause is. I did once in this
state encounter a situation where the "webkit" file directory entry was
broken/frozen and I had to re-start the app.
I am still trying to investigate the cause of this...
It could be that the timeout threshold is too low, at I think 2 seconds?
Maybe sometimes there is garbage collection happening or one of the copies
takes longer than 2 seconds and triggers the timeout...

**Comment by CaptainDoubleYou** [comment] 2013-12-30 19:16
It keep happening to me. THanks for getting back to me. Just thought to bring it up.

**Comment by kzahel** [comment] 2014-01-15 01:42
I'm increasing the "timeout" in the next version. I'll continue to monitor this and perhaps add some retry logic so that this will self correct. Stay tuned...

**Comment by kzahel** [comment] 2014-01-25 18:38
The timeout increase hasn't really fixed the problem.
I'm going to have to rewrite the diskio queue logic to split up diskio jobs to be more fine grained. It's going to take a bit of work... but it will help me identify exactly what the cause is and whether it's a chromium bug.

**Comment by kzahel** [comment] 2014-02-26 04:56
Almost have this issue fixed. Rewrote the whole diskio stuff... took several days. Going to do a lot of stress testing and then hopefully this bug is gone!!!

**Comment by kzahel** [comment] 2014-03-06 21:44
I've identified the bug: https://code.google.com/p/chromium/issues/detail?id=350080
Not sure what the workaround will be until this is fixed...

**Comment by kzahel** [comment] 2014-03-07 21:46
And it seems that's a "WontFix"
Once the app receives the "onSuspend" event I guess I am supposed to close it.
Well, for now I think this issue is "fixed" because I close the app or restart it when that event is received.

**Closed as completed by kzahel** 2014-03-07 21:46 UTC
